### ISSUE TITLE
Prediction method

### ISSUE THREAD

**Issue by agisga** [SciRuby/statsample-glm#14]
Am I seeing it correctly that there is no method to obtain predictions on new data from the fitted GLM model object?

That is, once I do something like

```Ruby
glm = Statsample::GLM.compute(train_data, y, :logit)
```

I would like to continue with something like

```Ruby
predictions = glm.predict(test_data)
```

**Comment by v0dro** [comment]
You're right. Adding as enhancement.

**Comment by lokeshh** [comment]
May I try adding this enhancement if it isn't such a big task? It would help me get familiarize with how `statsample-glm` works. 

So, if you are up for it. How should I go about doing it? I guess there's a function which I have to apply on `test_data`. I do not know what that function should be though.

**Comment by agisga** [comment]
@lokeshh Oh, I have already started working on it, sorry. Might take me a couple of days though, because I have exams this week.

**Comment by lokeshh** [comment]
No problem at all. I will find something else to get familiar with it.

**Comment by agisga** [comment]
@lokeshh I would suggest #4 if you have time. None of the methods have any docs. I will also open a couple new issues in a few days.

**Comment by lokeshh** [comment]
Thank you @agisga. Seems like the optimal thing for me.

**Comment by v0dro** [comment]
You can see this post for a general guideline: http://v0dro.github.io/blog/2014/09/21/code-generalized-linear-models-introduction-and-implementation-in-ruby/
