### ISSUE TITLE
Drop 1.9.3 support and update Travis with latest rubies

### ISSUE THREAD

**Issue by v0dro** [SciRuby/statsample-glm#22]
Rubies should ideally include JRuby too.

**Comment by v0dro** [comment]
@lokeshh

**Comment by lokeshh** [comment]
Where lies the Travis file to be edited to have the desired changes?

**Comment by agarie** [comment]
Lokesh, the Travis configuration file is called `.travis.yml` by default, as you can see [here](https://github.com/SciRuby/statsample-glm/blob/master/.travis.yml).

**Comment by v0dro** [comment]
#29
